# Generated by Django 6.0.1 on 2026-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
