# Generated by Django 6.0.1 on 2026-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviess', '0003_alter_movies_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fantasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='moviess.fantasy'),
        ),
    ]
