# Generated by Django 6.0.1 on 2026-02-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviess', '0004_fantasy_movies_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
