# Generated by Django 4.2.11 on 2026-02-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviess', '0005_movies_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='price',
        ),
    ]
